version: '3.3'

services:
  db:
    image: postgres:14
    container_name: postgres_db
    volumes:
      - postgres_vol:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=mindbox_app
    ports:
      - 5432:5432
  web:
    build: .
    container_name: django_web
    command: >
      sh -c "python fill_db.py &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/mindbox
    ports:
      - 8000:8000
    depends_on:
      - db
volumes:
  postgres_vol:
